### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by crz11111** [CoffeeMine/CoffeeMine#60]
Needs fix:
- [x] New issue needs to be implemented
- [x] Styling needs to be implemented

Would be nice:
- [x] Dates are too accurate
- [ ] Filtering

**Comment by RuthgerD** [comment]
* 5 hours

**Comment by AeroStun** [comment]
3h

**Comment by AeroStun** [comment]
2h
